@Test
public void testPromptForCredential() throws Exception {
    String[] args1 = { "create", "credential1", "-provider", jceksProvider };
    ArrayList<String> passwords = new ArrayList<String>();
    passwords.add("p@ssw0rd");
    passwords.add("p@ssw0rd");
    int rc = 0;
    CredentialShell shell = new CredentialShell();
    shell.setConf(new Configuration());
    shell.setPasswordReader(new MockPasswordReader(passwords));
    rc = shell.run(args1);
    assertEquals(0, rc);
    assertOutputContains("credential1 has been successfully created.");
    String[] args2 = { "check", "credential1", "-provider", jceksProvider };
    ArrayList<String> password = new ArrayList<String>();
    password.add("p@ssw0rd");
    shell.setPasswordReader(new MockPasswordReader(password));
    rc = shell.run(args2);
    assertEquals(0, rc);
    assertOutputContains("Password match success for credential1.");
    ArrayList<String> passwordError = new ArrayList<String>();
    passwordError.add("p@ssw0rderr");
    shell.setPasswordReader(new MockPasswordReader(password));
    rc = shell.run(args2);
    assertEquals(0, rc);
    assertOutputContains("Password match failed for credential1.");
    String[] args3 = { "delete", "credential1", "-f", "-provider", jceksProvider };
    rc = shell.run(args3);
    assertEquals(0, rc);
    assertOutputContains("credential1 has been successfully deleted.");
}
