@Test
public void aNonIntegerThrowsAnExceptionWithCustomName() {
    assertThatThrownBy(() -> new IntParam("foo", "customName")).isInstanceOfSatisfying(WebApplicationException.class, e -> {
        assertThat(e.getResponse().getStatus()).isEqualTo(400);
        assertThat(e.getResponse().getEntity()).isEqualTo(new ErrorMessage(400, "customName is not a number."));
    });
}
