@Test
public void testOnRouteRequestWhenInternalServerErrorExceptionInDiagnosticMode() throws Exception {
    FilterChain filterChain = Mockito.mock(FilterChain.class);
    Mockito.when(route.getFilterChain()).thenReturn(filterChain);
    InternalServerErrorException internalServerErrorException = new InternalServerErrorException("That's an InternalServerErrorException that should be handled by onError!");
    Mockito.when(filterChain.next(contextImpl)).thenThrow(internalServerErrorException);
    when(ninjaProperties.isDev()).thenReturn(true);
    when(ninjaProperties.getBooleanWithDefault(NinjaConstant.DIAGNOSTICS_KEY_NAME, true)).thenReturn(true);
    ninjaDefault.onRouteRequest(contextImpl);
    Result localResult = ninjaDefault.getInternalServerErrorResult(contextImpl, internalServerErrorException, null);
    assertThat(localResult.getRenderable(), CoreMatchers.instanceOf(DiagnosticError.class));
}
