@Test
public void testInterceptFutureWrongException() throws Throwable {
    CompletableFuture<String> future = new CompletableFuture<>();
    future.completeExceptionally(new RuntimeException("oops"));
    intercept(RuntimeException.class, "oops", () -> interceptFuture(IOException.class, "", future));
}
