@Test
void invokeWhenOperationIsInvalidShouldThrowException() throws MBeanException, ReflectionException {
    TestJmxOperation operation = new TestJmxOperation() {

        @Override
        public Object invoke(InvocationContext context) {
            throw new InvalidEndpointRequestException("test failure", "test");
        }
    };
    TestExposableJmxEndpoint endpoint = new TestExposableJmxEndpoint(operation);
    EndpointMBean bean = new EndpointMBean(this.responseMapper, null, endpoint);
    assertThatExceptionOfType(ReflectionException.class).isThrownBy(() -> bean.invoke("testOperation", NO_PARAMS, NO_SIGNATURE)).withRootCauseInstanceOf(IllegalArgumentException.class).withMessageContaining("test failure");
}
