@Test
public void testRetryAfterFailure() throws Exception {
    // Previous operation failed
    Server.Call call = newCall();
    int input = r.nextInt();
    Server.getCurCall().set(call);
    testServer.echo(input, input + 1, 5, false);
    testOperations(input, 25, 0, false, true, call);
}
